version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: crud-with-auth
    ports:
      - "4000:4000"
    # depends_on:
    #   - postgres
    volumes:
      - ./:/app

  redis:
    image: redis:6.2
    volumes:
      - "./tmp/redis:/data"
    ports:
      - "6333:6379"

  # postgres:
  #   image: postgres:13.4
  #   ports:
  #     - "5433:5432"