FROM golang:1.15.15-alpine3.14 as builder

RUN apk update && apk add build-base git

WORKDIR /app
COPY ../../go.mod ../../go.sum ./
RUN go mod download
COPY ../../ .

RUN go get github.com/markbates/refresh

CMD ["refresh", "run"]
