// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"crud-with-auth/api"
	"crud-with-auth/db"
)

// Injectors from wire.go:

func InitializeApp() *api.Api {
	providerDB := db.ProvideDB()
	apiApi := api.NewAPI(providerDB)
	return apiApi
}
